version: "3.7"

services:
    postgres:
        container_name: postgres
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data

    frontend:
        container_name: react-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        environment:
            - REACT_APP_API_URL=http://backend:9001
        ports:
            - '3003:3000'
        depends_on:
            - postgres
            - backend
    
    backend:
        container_name: spring-backend
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '9001:9001'
        depends_on:
            - postgres
        environment:
            # - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=demo
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
   postgres:
