services:
    postgres:
        container_name: postgres
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data

    frontend:
        container_name: react-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        ports:
            - '3003:3000'
        depends_on:
            - postgres
            - backend
    
    backend:
        container_name: spring-backend
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - postgres

volumes:
   postgres:
